src/main/java/com/psybergate/finance/web/controller/InvestmentController.java
package com.psybergate.finance.web.controller;

import static com.psybergate.finance.util.BigDecimalUtil.convert;
import static com.psybergate.finance.util.BigDecimalUtil.percentageToDecimal;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.SortedSet;
import java.util.TreeSet;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.el.MethodExpression;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import org.primefaces.PrimeFaces;
import org.primefaces.model.chart.Axis;
import org.primefaces.model.chart.AxisType;
import org.primefaces.model.chart.LineChartModel;
import org.primefaces.model.chart.LineChartSeries;

import com.psybergate.finance.domain.Customer;
import com.psybergate.finance.domain.interestbearinginstrument.InterestBearingMonth;
import com.psybergate.finance.domain.investment.Investment;
import com.psybergate.finance.service.customer.CustomerService;
import com.psybergate.finance.service.investment.InvestmentService;
import com.psybergate.finance.web.util.MethodExpressionUtil;

@ManagedBean(name = "investmentController")
@ViewScoped
public class InvestmentController {

	@EJB
	private InvestmentService investmentService;

	@Inject
	private CustomerService customerService;

	@Inject
	private CustomerSession customerSession;

	private Investment investment= new Investment();

	private LineChartModel lineModel;

	public InvestmentController() {
	}

	@PostConstruct
	public void init() {
		Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();

		String investmentId = params.get("id");

		if (investmentId != null) {
			investment = investmentService.getInvestment(Long.valueOf(investmentId));
			investment.updateMonths();
		} else {
			PrimeFaces current = PrimeFaces.current();
			current.executeScript("PF('new-forecast-dlg').show();");
		}
		
		update();
	}

	public void update() {
		Investment oldInvestment = investment;
		investment = new Investment(oldInvestment);
		investment.updateMonths();
		updateGraph();
	}

	public void addRateChangeEvent(int rateChangeMonth, BigDecimal rateChange) {
		investmentService.setNominalRateFor(investment, rateChangeMonth, percentageToDecimal(rateChange));
		updateGraph();
	}

	public void addDepositEvent(int depositMonth, BigDecimal deposit) {
		investmentService.deposit(investment, depositMonth, deposit.doubleValue());
		updateGraph();
	}

	public void addWithdrawalEvent(int withdrawalMonth, BigDecimal withdrawal) {
		investmentService.withdraw(investment, withdrawalMonth, withdrawal.doubleValue());
		updateGraph();
	}

	public void addMonthlyContributionChangeEvent(int contributionMonth, BigDecimal contributionAmount) {
		investment.addMonthlyContributionFor(contributionMonth, contributionAmount);
		updateGraph();
	}

	public void addInvestment() {
		Customer customer = customerSession.getCustomer();
		customerService.addForecast(customer, investment);
	}

	public Investment getInvestment() {
		return investment;
	}

	public void setName(String name) {
		investment.setName(name);
	}

	public String getName() {
		return investment.getName();
	}

	public void setPrincipal(BigDecimal principal) {
		investment.setPrincipal(principal);
	}

	public BigDecimal getPrincipal() {
		return investment.getPrincipal();
	}

	public void setNominalRate(BigDecimal nominalRate) {
		investment.setNominalRate(nominalRate);
	}

	public BigDecimal getNominalRate() {
		return investment.getNominalRate();
	}

	public BigDecimal getNominalRatePercentage() {
		BigDecimal nominalRate = investment.getNominalRate();
		if (nominalRate == null) return BigDecimal.ZERO;
		return investment.getNominalRate().multiply(BigDecimal.valueOf(100));
	}

	public void setNominalRatePercentage(BigDecimal nominalRate) {
		BigDecimal nominalRateAsDecimal = nominalRate.divide(BigDecimal.valueOf(100), 9, RoundingMode.HALF_UP).setScale(3,
				RoundingMode.HALF_EVEN);
		investment.setNominalRate(nominalRateAsDecimal);
	}

	public BigDecimal getEffectiveRate() {
		try {
			return investment.getEffectiveRate().multiply(convert(10));
		} catch ( NullPointerException e ) {
			return BigDecimal.ZERO;
		}
	}

	public void setTermInMonths(int termInMonths) {
		investment.setTermInMonths(termInMonths);
	}

	public int getTermInMonths() {
		return investment.getTermInMonths();
	}

	public List<InterestBearingMonth> getMonths() {
		return investment.getMonths();
	}

	public void setMonthlyContribution(BigDecimal amount) {
		investment.setMonthlyContribution(amount);
	}

	public BigDecimal getMonthlyContribution() {
		return investment.getMonthlyContribution();
	}

	public void setBankFees(BigDecimal amount) {
		investment.setBankFees(amount);
	}

	public BigDecimal getBankFees() {
		return investment.getBankFees();
	}

	public BigDecimal getCumalitiveInterest() {
		return investment.getCumalitiveInterest();
	}

	public BigDecimal getTotalInterest() {
		return investmentService.calculateTotalInterestEarned(investment);
	}

	public BigDecimal getClosingBalance() {
		return investmentService.calculateClosingBalance(investment);
	}

	public void addBankFeesEvent(int bankingFeesMonth, BigDecimal bankingFees) {
		investment.addBankFeesFor(bankingFeesMonth, bankingFees);
		updateGraph();
	}

	public BigDecimal getTotalBankFees() {
		return investment.getTotalBankFees();
	}

	public void updateGraph() {
		lineModel = new LineChartModel();
		LineChartSeries s = new LineChartSeries();
		String name = (investment.getName() != null) ? investment.getName() : "Investment";
		s.setLabel(name);
		List<InterestBearingMonth> months = new ArrayList<>();

		months.addAll(getMonths());

		int numOfMonths = investment.getTermInMonths() + 1;
		int tick;
		int pointToTake = 1;

		if (numOfMonths <= 60) {
			tick = 3;
		}
		if (numOfMonths < 120) {
			tick = 6;
		}
		else {
			tick = 12;
			pointToTake = 3;
		}

		int i = 1;
		for (InterestBearingMonth month : months) {
			if (i % pointToTake == 0) {
				s.set(i, month.getClosing());
			}
			i++;
		}

		lineModel.addSeries(s);
		lineModel.setLegendPosition("e");
		Axis y = lineModel.getAxis(AxisType.Y);
		y.setMin(investment.getPrincipal());
		SortedSet<BigDecimal> capitalAmounts = new TreeSet<BigDecimal>();
		investment.getMonths().forEach(m -> capitalAmounts.add(m.getOpening()));
		capitalAmounts.add(investment.getClosingBalance());
		BigDecimal maxValueInSet = capitalAmounts.last();
		Double maxValue = maxValueInSet.multiply(convert(1.1)).doubleValue();
		y.setMax(maxValue);
		y.setLabel("Closing Balance");

		Axis x = lineModel.getAxis(AxisType.X);
		x.setMin(0);
		x.setMax(months.size() - 1);
		x.setTickInterval(String.valueOf(tick));
		x.setLabel("Month");
	}

	public LineChartModel getLineModel() {
		return lineModel;
	}

	public String getInvestmentTitle() {
		if (investment.getId() != null) { return investment.getName(); }
		return "New Investment";
	}


	public void addInvestment(BigDecimal principal, BigDecimal nominalRate, BigDecimal monthlyContribution,
			BigDecimal bankFees, int termInMonths) {
		Investment newInvestment = new Investment(principal, percentageToDecimal(nominalRate), monthlyContribution,
				bankFees, termInMonths);
		investment = newInvestment;
		investment.updateMonths();
		update();
	}

	public void editInvestment(BigDecimal principal, BigDecimal nominalRate, BigDecimal monthlyContribution,
			BigDecimal bankFees, int termInMonths) {
		investment.setPrincipal(principal);
		investment.setNominalRate(percentageToDecimal(nominalRate));
		investment.setMonthlyContribution(monthlyContribution);
		investment.setBankFees(bankFees);
		investment.setTermInMonths(termInMonths);
		investment.updateMonths();
		update();
	}

	public MethodExpression getEditForecast() {
		Class<?> expectedReturnType = void.class;
		Class<?>[] expectedParamTypes = { BigDecimal.class, BigDecimal.class, BigDecimal.class, BigDecimal.class,
				int.class };
		MethodExpression methodExpression = MethodExpressionUtil.createMethodExpression(
				"#{investmentController.editInvestment( investmentDialog.initialDeposit, investmentDialog.nominalRate,"
						+ " investmentDialog.monthlyContribution, investmentDialog.bankFees, investmentDialog.termInMonths)}",
				expectedReturnType, expectedParamTypes);
		return methodExpression;
	}

	public MethodExpression getNewForecast() {
		Class<?> expectedReturnType = void.class;
		Class<?>[] expectedParamTypes ={ BigDecimal.class, BigDecimal.class, BigDecimal.class, BigDecimal.class,
				int.class };
		MethodExpression methodExpression = MethodExpressionUtil.createMethodExpression(
				"#{investmentController.addInvestment( investmentDialog.initialDeposit, investmentDialog.nominalRate,"
						+ " investmentDialog.monthlyContribution, investmentDialog.bankFees, investmentDialog.termInMonths)}",
				expectedReturnType, expectedParamTypes);
		return methodExpression;
	}

	public MethodExpression getOpenForecast() {
//	MethodExpressionUtil.createMethodExpression(methodExpression, expectedReturnType, expectedParamTypes)
		return null;
	}

	public MethodExpression getSaveForecast() {
		Class<?> expectedReturnType = void.class;
		Class<?>[] expectedParamTypes = {};
		MethodExpression methodExpression = MethodExpressionUtil.createMethodExpression("#{investmentController.update}",
				expectedReturnType, expectedParamTypes);
		return methodExpression;
	}

	public Investment getInstrument() {
		return investment;
	}
}

src/main/java/com/psybergate/finance/web/controller/truecost/AbstractTrueCostController.java
package com.psybergate.finance.web.controller.truecost;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.el.MethodExpression;
import javax.inject.Inject;

import org.primefaces.model.charts.ChartData;
import org.primefaces.model.charts.ChartDataSet;
import org.primefaces.model.charts.line.LineChartDataSet;
import org.primefaces.model.charts.line.LineChartModel;
import org.primefaces.model.charts.line.LineChartOptions;
import org.primefaces.model.charts.optionconfig.title.Title;

import com.psybergate.finance.domain.interestbearinginstrument.InterestBearingInstrument;
import com.psybergate.finance.web.Colour;
import com.psybergate.finance.web.controller.CustomerSession;

public abstract class AbstractTrueCostController {
	
	@Inject
	protected CustomerSession customerSession;
	
	protected LineChartModel lineModel;
	
	protected LineChartDataSet lineChartImpactOfEvents = new LineChartDataSet();
	
	protected List<String> savedInstruments = new ArrayList<>();

	protected List<String> choices = new ArrayList<>();

	protected String selected = "";
	
	protected Map<String, InterestBearingInstrument> instruments;
	
	protected InterestBearingInstrument investment;

	protected int fooNum;
	
	protected Colour withoutEventsColour = Colour.BLUE;
	
	protected Colour withEventsColour = Colour.RED;

	@PostConstruct
	public void init() {
		lineModel = new LineChartModel();
		instruments = getFromService();
		instruments.keySet().forEach(k -> choices.add(k));
		instruments.keySet().forEach(k -> savedInstruments.add(k));
		setupLineModel();
	}

	protected abstract Map<String, InterestBearingInstrument> getFromService();
	
	protected abstract String getType();

	public String getSelected() {
		return selected;
	}

	public void setSelected(String selected) {
		this.selected = selected;
	}

	public List<String> getChoices() {
		return choices;
	}

	public void setupLineModel() {
		ChartData data = new ChartData();

		// Options
		LineChartOptions options = new LineChartOptions();
		Title title = new Title();
		title.setDisplay(true);
		title.setText("Comparison");
		options.setTitle(title);

		lineModel.setOptions(options);
		lineModel.setData(data);
	}

	public void update() {
		updateSelectedInstrument(getSelected());
	}

	public void updateSelectedInstrument(String selected) {
		ChartData data = new ChartData();
		InterestBearingInstrument instrument = null;

			instrument = instruments.get(selected);
			
			if(instrument != null) {
				LineChartDataSet originalDataSet = null;
				
				if(savedInstruments.contains(selected))
				{
					originalDataSet = createLineChartDataSet(createInstrumentImpactedByEvents(instrument), selected+" before Events", withoutEventsColour);
					investment = instrument;
					lineChartImpactOfEvents = createLineChartDataSet(instrument, selected, withEventsColour);
					
				}else {
					originalDataSet = createLineChartDataSet(instrument, selected, withoutEventsColour);
					investment = createInstrumentImpactedByEvents(instrument);
					lineChartImpactOfEvents = createLineChartDataSet(investment, selected + " After Events", withoutEventsColour);
				}
				
				data.addChartDataSet(originalDataSet);

				data.addChartDataSet(lineChartImpactOfEvents);

					List<String> labels = getLabels(instrument);
					data.setLabels(labels);			
					lineModel.setData(data);
		}
	}

	protected List<String> getLabels(InterestBearingInstrument instrument) {
		List<String> labels;
		labels = new ArrayList<>();
		int termInMonths = instrument.getTermInMonths();

		for (int i = 1; i <= termInMonths; i++) {
			labels.add(String.valueOf(i));
		}
		return labels;
	}

	public LineChartDataSet createLineChartDataSet(InterestBearingInstrument instrument, String label, Colour colour) {
		return createLineChartDataSet(instrument, label, colour.getRGB());
	}

	public LineChartDataSet createLineChartDataSet(InterestBearingInstrument instrument, String label, String colourRGB) {
		LineChartDataSet dataSet = new LineChartDataSet();
		List<Number> values = new ArrayList<>();

		getChartPoints(instrument, values);
		
		dataSet.setData(values);
		dataSet.setFill(true);
		dataSet.setLabel(label);
		dataSet.setBorderColor(colourRGB);
		dataSet.setLineTension(0.1);
		return dataSet;
	}

	public LineChartModel getModel() {
		return lineModel;
	}
	
	public abstract MethodExpression getExpression();
	
	public void getChartPoints(InterestBearingInstrument instrument, List<Number> values) {
		instrument.getMonths().forEach(month -> values.add(month.getOpening()));
		values.add(instrument.getClosingBalance());
	}

	public void addInstrumentToSelection(InterestBearingInstrument instrument) {
		fooNum++;
		String label = getType() + fooNum;
		instruments.put(label, instrument);
		choices.add(label);
		selected= label;

		updateSelectedInstrument(selected);
	}
	
	public void updateAfterEvent() {
		lineChartImpactOfEvents = createLineChartDataSet(investment, selected + " After Events", Colour.RED);
		ChartData data = lineModel.getData();
		List<ChartDataSet> dataSets = data.getDataSet();
		dataSets.set(1, lineChartImpactOfEvents);
	}

	public abstract InterestBearingInstrument createInstrumentImpactedByEvents(InterestBearingInstrument original);
	
	
}

src/main/webapp/WEB-INF/templates/comparison-template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<body>
	<ui:composition xmlns="http://www.w3.org/1999/xhtml"
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:p="http://primefaces.org/ui"
		xmlns:h="http://java.sun.com/jsf/html" template="template.xhtml">

		<ui:define name="body">

		<style type="text/css">
			.ui-icon .ui-icon-close, .ui-icon .ui-icon-search, .ui-icon .ui-icon-circle-close
			{ text-indent: 0; text-align: center; width: auto; height: auto; }

			.ui-icon-close:before { 
				content: "\f00d"; 
			font-family: "Font Awesome 5 Free"!important;
    		font-weight: 900;}

    		.ui-icon-search:before { content: "\f688"!important;
    	font-family: "Font Awesome 5 Free"!important;
    		font-weight: 900;}

    		.ui-icon-circle-close:before { content: "\f057"; 
    		font-family: "Font Awesome 5 Free"!important;
    		font-weight: 900;}
		</style>


		
		  <p:panel id="basic" header="#{panelTitle}"  style="margin-bottom:20px" toggleable="true">
      
        <div class="ui-g ui-fluid">
          <div class="ui-g-6">
             <h:form>
                         <h:outputLabel for="multiple" value="#{userInstrumentsLabel}" style="margin-right: 10px"/>
              <p:selectCheckboxMenu id="multiple" value="#{eventImpactController.selected}"  multiple="true"
                              filter="true" filterMatchMode="startsWith" panelStyle="width:250px">
                <f:selectItems value="#{eventImpactController.choices}" />
                  <p:ajax event="change" update="comparisonLineChart"  listener="#{eventImpactController.update}"/>
              </p:selectCheckboxMenu>
          </h:form>
          </div>
          <div class="ui-g-6">
            <h:outputLabel for="multiple" value="or" style="margin-right: 10px"/>
            <p:commandButton value="#{addButtonText}" onclick="PF('#{addWidgetVar}').show();" type="button" icon="fa fa-plus-circle">
                <p:ajax event="dialogReturn"  update="comparisonLineChart" />
          </p:commandButton>

          </div>
        </div>
    </p:panel>

      <p:panel id="graph" style="margin-bottom:20px">
     <p:lineChart id="comparisonLineChart"  model="#{eventImpactController.model}" style="width: 100%; height: 500px;"/>
      </p:panel>

        <ui:include src="inc/#{inputFormFileName}.xhtml">
          <ui:param name="submitAction" value="#{eventImpactController.expression}" />
          <ui:param name="widgetVar" value="#{addWidgetVar}" />
          <ui:param name="addInstrumentTitle" value="#{addInstrumentTitle}" />
        </ui:include>

     
		</ui:define>

	</ui:composition>
</body>
</html>

src/main/webapp/WEB-INF/templates/forecast-template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<body>
	<ui:composition xmlns="http://www.w3.org/1999/xhtml"
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:p="http://primefaces.org/ui"
		xmlns:h="http://java.sun.com/jsf/html" template="template.xhtml">


        <ui:define name="body">
        <style>
        #forecast-events.ui-menu {
    width: 18em!important;}

     	@media (max-width: 768px) {
                body div.mobile-menus {
                    display:block!important;
                }

                .non-mobile-menus button.ui-button{
                    display: none!important;
                }

                td.optional-for-mobile{
                	display: none!important;	
                }

            }

        @media (min-width: 769px) {
                body div.mobile-menus {
                    display: none!important;
                }

                .non-mobile-menus button.ui-button {
                    display: block!important;
                }

                td.optional-for-mobile{
                	display: block!important;	
                }
            }    
        </style>

        	<div class="ui-g ui-fluid mobile-menus">
        		<h:form>
        		<div class="ui-g-6">
                            <p:menuButton id="forecast-events" value="Add Event" icon="fa fa-bolt">
                                <p:menuitem value="Rate Change" icon="fa fa-percentage"
                                    onclick="PF('dlg').show();" />
                                <p:menuitem value="Bank Fee Change" icon="fa fa-university"
                                    onclick="PF('bank-fees-dlg').show();" />
                                    
                                <ui:insert name="events-menu-extra" />
                                
                                <p:menuitem value="Make Deposit" icon="fa fa-arrow-circle-up"
                                    onclick="PF('deposit-dlg').show();" />
                                <p:menuitem value="Make Withdrawal"
                                    icon="fa fa-arrow-circle-down"
                                    onclick="PF('withdrawal-dlg').show();" />
                            </p:menuButton>      
                 </div>
                 <div class="ui-g-6">             
                             <p:menuButton value="Forecast Options" icon="fa fa-cog">
                                <p:menuitem value="New Forecast" icon="fa fa-plus-circle"
                                    onclick="PF('new-forecast-dlg').show();" />

                                <p:menuitem value="Edit Forecast" icon="fa fa-pencil"
                                    onclick="PF('edit-forecast-dlg').show();" />
                               
                                <p:menuitem value="Save Forecast"
                                    icon="fa fa-save"
                                    onclick="PF('save-forecast-dlg').show();" />
                            </p:menuButton>
                     </div>
                        	</h:form>
                 </div>
        	


			<div class="row">
				<div class="col-md-3 col-sm-6 col-xs-12">
					<ui:insert name="info-block-1" />
				</div>
				<!-- /.col -->
				<div class="col-md-3 col-sm-6 col-xs-12">
					<ui:insert name="info-block-2" />
				</div>
				<!-- /.col -->
				<!-- fix for small devices only -->
				<div class="clearfix visible-sm-block"></div>

				<div class="col-md-3 col-sm-6 col-xs-12">
					<ui:insert name="info-block-3" />
				</div>
				<!-- /.col -->
				<div class="col-md-3 col-sm-6 col-xs-12">
					<ui:insert name="info-block-4" />
				</div>
			</div>
			<!-- /.row -->

		         
                <p:tabView styleClass="card no-border myTabview">
                    <p:tab title="Tabular">
                        <f:facet name="actions">
                        <h:form>
                            <p:menuButton id="forecast-events" value="Add Event" icon="fa fa-bolt" class="non-mobile-menus">
                                <p:menuitem value="Rate Change" icon="fa fa-percentage"
                                    onclick="PF('dlg').show();" />
                                <p:menuitem value="Bank Fee Change" icon="fa fa-university"
                                    onclick="PF('bank-fees-dlg').show();" />
                                <ui:insert name="events-menu-extra" />
                                
                                <p:menuitem value="Make Deposit" icon="fa fa-arrow-circle-up"
                                    onclick="PF('deposit-dlg').show();" />
                                <p:menuitem value="Make Withdrawal"
                                    icon="fa fa-arrow-circle-down"
                                    onclick="PF('withdrawal-dlg').show();" />
                            </p:menuButton>                   
                             <p:menuButton value="Forecast Options" icon="fa fa-cog" class="non-mobile-menus">
                                <p:menuitem value="New Forecast" icon="fa fa-plus-circle"
                                    onclick="PF('new-forecast-dlg').show();" />

                                <p:menuitem value="Edit Forecast" icon="fa fa-pencil"
                                    onclick="PF('edit-forecast-dlg').show();" />
                               
                                <p:menuitem value="Save Forecast"
                                    icon="fa fa-save"
                                    onclick="PF('save-forecast-dlg').show();" />
                            </p:menuButton>
                        	</h:form>

						</f:facet>
					<ui:insert name="output-tab-tabular" />
					</p:tab>
					<p:tab title="Graph">
						<ui:insert name="output-tab-graph" />
					</p:tab>
					<ui:insert name="output-tab-extra" />
				</p:tabView>


                <ui:include src="inc/#{inputFormFileName}.xhtml">
          			<ui:param name="submitAction" value="#{eventImpactController.newForecast}" />
          			<ui:param name="widgetVar" value="new-forecast-dlg" />
          			<ui:param name="addInstrumentTitle" value="Add #{instrumentType}" />
					<ui:param name="giveFullForm" value="true" />
        		</ui:include>

        		<ui:include src="inc/#{inputFormFileName}.xhtml">
          			<ui:param name="submitAction" value="#{eventImpactController.openForecast}" />
          			<ui:param name="widgetVar" value="open-forecast-dlg" />
          			<ui:param name="addInstrumentTitle" value="Open #{instrumentType}" />
        		</ui:include>

        		<ui:include src="inc/#{inputFormFileName}.xhtml">
          			<ui:param name="submitAction" value="#{eventImpactController.editForecast}" />
          			<ui:param name="widgetVar" value="edit-forecast-dlg" />
          			<ui:param name="addInstrumentTitle" value="Edit #{instrumentType}" />
          			<ui:param name="giveFullForm" value="true" />
          			<ui:param name="instrument" value="#{eventImpactController.instrument}" />
        		</ui:include>

			<ui:insert name="dialogs" />

		</ui:define>

	</ui:composition>
</body>
</html>