src/main/java/com/psybergate/finance/web/controller/PropertyBondController.java
package com.psybergate.finance.web.controller;

import static com.psybergate.finance.util.BigDecimalUtil.convert;
import static com.psybergate.finance.util.BigDecimalUtil.decimalToPercentage;
import static com.psybergate.finance.util.BigDecimalUtil.percentageToDecimal;
import static com.psybergate.finance.util.BigDecimalUtil.sumList;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.SortedSet;
import java.util.TreeSet;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.el.MethodExpression;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import org.primefaces.PrimeFaces;
import org.primefaces.model.chart.Axis;
import org.primefaces.model.chart.AxisType;
import org.primefaces.model.chart.LineChartModel;
import org.primefaces.model.chart.LineChartSeries;
import org.primefaces.model.charts.ChartData;
import org.primefaces.model.charts.pie.PieChartDataSet;
import org.primefaces.model.charts.pie.PieChartModel;

import com.psybergate.finance.domain.Customer;
import com.psybergate.finance.domain.interestbearinginstrument.InterestBearingMonth;
import com.psybergate.finance.domain.propertybond.PropertyBond;
import com.psybergate.finance.service.customer.CustomerService;
import com.psybergate.finance.service.propertybond.PropertyBondService;
import com.psybergate.finance.web.util.MethodExpressionUtil;

@ManagedBean(name = "propertyBondController")
@ViewScoped
public class PropertyBondController {

	@EJB
	private PropertyBondService propertyBondService;

	@Inject
	private CustomerService customerService;

	@Inject
	private CustomerSession customerSession;

	protected PropertyBond propertyBond = new PropertyBond();

	private LineChartModel lineModel = new LineChartModel();

	@PostConstruct
	public void init() {
		Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();

		String propertyBondId = params.get("id");

		if (propertyBondId != null) {
			propertyBond = propertyBondService.getPropertyBond(Long.valueOf(propertyBondId));
			update();
		}
		else {
			propertyBond = new PropertyBond();
			PrimeFaces current = PrimeFaces.current();
			current.executeScript("PF('new-forecast-dlg').show();");
		}
	}

	public void addPropertyBond() {
		Customer customer = customerSession.getCustomer();
		customerService.addForecast(customer, propertyBond);
	}

	public void addRateChangeEvent(int rateChangeMonth, BigDecimal rateChange) {
		propertyBond.setNominalRateFor(rateChangeMonth, percentageToDecimal(rateChange));
		update();
	}

	public void update() {
		propertyBond.updateMonths();
		updateGraph();
	}

	public void useMinimumRepayment(int startMonth, int endMonth) {
		propertyBond.useMinimumRepayment(startMonth, endMonth);
	}

	public void addDepositEvent(int depositMonth, BigDecimal deposit) {
		propertyBond.addDepositFor(depositMonth, deposit);
		update();
	}

	public void addWithdrawalEvent(int withdrawalMonth, BigDecimal withdrawal) {
		propertyBond.addWithdrawalFor(withdrawalMonth, withdrawal);
		update();
	}

	public void addBankFeesEvent(int bankingFeesMonth, BigDecimal bankingFees) {
		propertyBond.addBankFeesFor(bankingFeesMonth, bankingFees);
		update();
	}

	public void addMonthlyRepaymentChangeEvent(int repaymentMonth, BigDecimal repaymentFees) {
		propertyBond.addMonthlyRepaymentFor(repaymentMonth, repaymentFees);
		update();
	}

	public PieChartModel getUpfrontCashPieModel() {
		PieChartModel pieModel = new PieChartModel();

		pieModel = new PieChartModel();
		ChartData data = new ChartData();

		PieChartDataSet dataSet = new PieChartDataSet();
		List<Number> values = new ArrayList<>();
		values.add(propertyBond.getTransferTax());
		values.add(propertyBond.getLegalFees());
		values.add(propertyBond.getBondCosts());
		dataSet.setData(values);

		List<String> bgColors = new ArrayList<>();
		bgColors.add("rgb(0, 165, 90)");
		bgColors.add("rgb(0, 192, 239)");
		bgColors.add("rgb(243, 156, 18)");
		dataSet.setBackgroundColor(bgColors);

		data.addChartDataSet(dataSet);
		List<String> labels = new ArrayList<>();
		labels.add("Transfer Duty");
		labels.add("Legal Fees");
		labels.add("Bond Costs");
		data.setLabels(labels);

		pieModel.setData(data);

		return pieModel;
	}

	public PieChartModel getTotalBondCostPieModel() {
		PieChartModel pieModel = new PieChartModel();

		pieModel = new PieChartModel();
		ChartData data = new ChartData();

		List<BigDecimal> withdrawals = new ArrayList<>();
		propertyBond.getMonths().forEach(m -> withdrawals.add(m.getTotalWithdrawalAmount()));

		BigDecimal withdrawalsTotal = sumList(withdrawals);

		PieChartDataSet dataSet = new PieChartDataSet();
		List<Number> values = new ArrayList<>();
		values.add(propertyBond.getCumalitiveInterest());
		values.add(propertyBond.getTotalBankFees());
		values.add(propertyBond.getPrincipal());
		values.add(withdrawalsTotal);
		dataSet.setData(values);

		List<String> bgColors = new ArrayList<>();
		bgColors.add("rgb(221, 75, 57)");
		bgColors.add("rgb(0, 165, 90)");
		bgColors.add("rgb(0, 192, 239)");
		bgColors.add("rgb(96, 92, 168)");
		dataSet.setBackgroundColor(bgColors);

		data.addChartDataSet(dataSet);
		List<String> labels = new ArrayList<>();
		labels.add("Cumalitive Interest");
		labels.add("Bank Fees");
		labels.add("Principal");
		labels.add("Withdrawals");
		data.setLabels(labels);

		pieModel.setData(data);

		return pieModel;
	}

	public void updateGraph() {
		lineModel = new LineChartModel();
		LineChartSeries s = new LineChartSeries();
		s.setLabel("Forecast");
		List<InterestBearingMonth> months = new ArrayList<>();
		months.addAll(getMonths());

		int i = 0;
		for (InterestBearingMonth month : months) {
			if (i % 3 == 0) {
				s.set(i, month.getClosing());
			}
			i++;
		}

		lineModel.addSeries(s);
		lineModel.setLegendPosition("e");
		Axis y = lineModel.getAxis(AxisType.Y);
		y.setMin(0);
		SortedSet<BigDecimal> outstandingPrincipalAmounts = new TreeSet<BigDecimal>();
		List<InterestBearingMonth> propertyBondMonths = propertyBond.getMonths();

		Double maxValue = 0d;
		if (propertyBondMonths.size() > 0) {
			propertyBondMonths.forEach(m -> outstandingPrincipalAmounts.add(m.getOpening()));
			BigDecimal maxValueInSet = outstandingPrincipalAmounts.last();
			maxValue = maxValueInSet.multiply(convert(1.2)).doubleValue();
		}

		y.setMax(maxValue);
		y.setLabel("Principal");

		int tick;

		if (maxValue <= 500_000) {
			tick = 50_000;
		}
		else if (maxValue < 1_500_001) {
			tick = 150_000;
		}
		else if (maxValue < 2_000_001) {
			tick = 500_000;
		}
		else if (maxValue < 6_000_001) {
			tick = 750_000;
		}
		else {
			tick = 1_000_000;
		}

		y.setTickInterval(String.valueOf(tick));

		Axis x = lineModel.getAxis(AxisType.X);
		x.setMin(0);
		x.setMax(propertyBond.getTermInMonths());
		x.setTickInterval("12");
		x.setLabel("Month");
	}

	public LineChartModel getLineModel() {
		return lineModel;
	}

	public String getCalendarColour() {
		if (propertyBond.getFinalPaymentMonth() < 0) return "red";
		return "green";
	}

	public String getCalendarIcon() {
		if (propertyBond.getFinalPaymentMonth() < 0) return "calendar-times";
		return "calendar-check";
	}

	public String getFinalMonthTitle() {
		if (propertyBond.getFinalPaymentMonth() < 0) return "";
		return "Paid off in month";
	}

	public String getFinalMonthBody() {
		if (propertyBond.getFinalPaymentMonth() < 0) return "Not paid off.";
		return String.valueOf(propertyBond.getFinalPaymentMonth());
	}

	public String getName() {
		return propertyBond.getName();
	}

	public void setName(String name) {
		propertyBond.setName(name);
	}

	public BigDecimal getBankFees() {
		return propertyBond.getBankFees();
	}

	public void setBankFees(BigDecimal bankFees) {
		propertyBond.setBankFees(bankFees);
	}

	public int getTermInMonths() {
		return propertyBond.getTermInMonths();
	}

	public void setTermInMonths(int termInMonths) {
		propertyBond.setTermInMonths(termInMonths);
	}

	public BigDecimal getPrincipal() {
		return propertyBond.getPrincipal();
	}

	public BigDecimal getInitialDepositRate() {
		return decimalToPercentage(propertyBond.getInitialDepositRate());
	}

	public void setInitialDepositRate(BigDecimal initialDepositRate) {
		propertyBond.setInitialDepositRate(percentageToDecimal(initialDepositRate));
	}

	public BigDecimal getInitialDeposit() {
		return propertyBond.getInitialDeposit();
	}

	public BigDecimal getClosingBalance() {
		return propertyBond.getClosingBalance();
	}

	public BigDecimal getPurchasePrice() {
		return propertyBond.getPurchasePrice();
	}

	public void setPurchasePrice(BigDecimal purchasePrice) {
		propertyBond.setPurchasePrice(purchasePrice);
	}

	public BigDecimal getCumalitiveInterest() {
		return propertyBond.getCumalitiveInterest();
	}

	public BigDecimal getMonthlyRepayment() {
		return propertyBond.getMonthlyRepayment();
	}

	public void setMonthlyRepayment(BigDecimal repayment) {
		propertyBond.setMonthlyRepayment(repayment);
	}

	public BigDecimal getBondCosts() {
		return propertyBond.getBondCosts();
	}

	public BigDecimal getTotalBondCost() {
		return propertyBond.getTotalBondCost();
	}

	public BigDecimal getLegalFees() {
		return propertyBond.getLegalFees();
	}

	public BigDecimal getTransferTax() {
		return propertyBond.getTransferTax();
	}

	public BigDecimal getTotalCashRequiredUpfront() {
		return propertyBond.getTotalCashRequiredUpfront();
	}

	public BigDecimal getOutstandingPrincipalFor(int monthNum) {

src/main/webapp/WEB-INF/templates/inc/column-monetary-amount.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html">
<body>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:pe="http://primefaces.org/ui/extensions">

    <p:column headerText="#{header}" priority="#{priority}">
        <ui:include src="monetary-amount.xhtml">
            <ui:param name="amount" value="#{amount}" />
        </ui:include>
    </p:column>
    
</ui:composition>
</body>
</html>

src/main/webapp/WEB-INF/templates/inc/column-percentage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html">
<body>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:pe="http://primefaces.org/ui/extensions">

    <p:column headerText="#{header}" priority="#{priority}">
        <h:outputText value="#{rate}">
            <f:convertNumber type="percent" maxFractionDigits="3" />
        </h:outputText>
    </p:column>
    
</ui:composition>
</body>
</html>

src/main/webapp/WEB-INF/templates/inc/dialog-add-event-monetary-amount.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html">
<body>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:pe="http://primefaces.org/ui/extensions">

           
                <p:dialog widgetVar="#{widgetVarName}" modal="true"  appendTo="#{whereToAppend}">
                    <f:facet name="header">
                        <i class="fa fa-#{iconName}"></i> #{headerTitle}
                        </f:facet>
                         <h:form>

                    <div class="ui-g ui-fluid">
                        <div class="ui-g-4">
                            <label>#{amountLabel}</label>
                        </div>
                        <div class="ui-g-4">
                            <label>#{monthLabel}</label>
                        </div>
                    </div>
                    <div class="ui-g ui-fluid">
                        <div class="ui-g-4">
                            <p:inputNumber value="#{eventDialog.amount}"
                                required="true" decimalSeparator="," thousandSeparator="&nbsp;" emptyValue="0"
                        decimalPlaces="2" minValue="0" />
                        </div>
                        <div class="ui-g-4">
                            <p:inputNumber 
                                value="#{eventDialog.month}" required="true" decimalPlaces="0"
                                emptyValue="empty" minValue="1" />
                        </div>

                        <div class="ui-g-4">
                            <p:commandButton value="Submit"
                                action="#{submitEvent}"
                                ajax="false" />
                        </div>
                    </div>
                    </h:form>
                </p:dialog>
            

</ui:composition>
</body>
</html>

src/main/webapp/WEB-INF/templates/inc/dialog-add-event-percentage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html">
<body>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:pe="http://primefaces.org/ui/extensions">

           
                <p:dialog widgetVar="#{widgetVarName}" modal="true"  appendTo="#{whereToAppend}">
                    <f:facet name="header">
                        <i class="fa fa-#{iconName}"></i> #{headerTitle}
                        </f:facet>
                         <h:form>

                    <div class="ui-g ui-fluid">
                        <div class="ui-g-4">
                            <label>#{amountLabel}</label>
                        </div>
                        <div class="ui-g-4">
                            <label>#{monthLabel}</label>
                        </div>
                    </div>
                    <div class="ui-g ui-fluid">
                        <div class="ui-g-4">
                            <p:inputNumber value="#{eventDialog.amount}"
                                required="true" symbol="%" symbolPosition="s" decimalPlaces="1"
                        emptyValue="0" minValue="0" />
                        </div>
                        <div class="ui-g-4">
                            <p:inputNumber 
                                value="#{eventDialog.month}" required="true" decimalPlaces="0"
                                emptyValue="empty" minValue="1" />
                        </div>

                        <div class="ui-g-4">
                            <p:commandButton value="Submit"
                                action="#{submitEvent}"
                                ajax="false" />
                        </div>
                    </div>
                    </h:form>
                </p:dialog>
            

</ui:composition>
</body>
</html>

src/main/webapp/WEB-INF/templates/inc/events-menu-investment.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    >
<body>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:pe="http://primefaces.org/ui/extensions"
                template="events-menu.xhtml">

 <ui:define name="events-menu-extra" >
            <p:menuitem value="Change Monthly Contribution"
                                    icon="fa fa-money-bill-wave"
                                    onclick="PF('contribution-dlg').show();" />
</ui:define>

<ui:define name="extra-dialogs"> 

        <ui:include src="dialog-add-event-monetary-amount.xhtml">
            <ui:param name="submitEvent" value="#{investmentEventImpact.monthlyContributionDialogEvent}" />
            <ui:param name="widgetVarName" value="contribution-dlg" />
            <ui:param name="updateTarget" value="comparisonLineChart"/>
            <ui:param name="whereToAppend" value="graph" />
            <ui:param name="iconName" value="money-bill-wave" />
            <ui:param name="headerTitle" value="Change Regular Contribution" />
            <ui:param name="amountLabel" value="New Regular Contribution Amount" />
            <ui:param name="monthLabel" value="Starting From Month" />
        </ui:include>  
</ui:define>
</ui:composition>
</body>
</html>

src/main/webapp/WEB-INF/templates/inc/info-block-percentage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html">
<body>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:pe="http://primefaces.org/ui/extensions">

<div class="info-box">
                        <span class="info-box-icon bg-#{colour}"><i
                            class="fa fa-#{iconName}"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">#{title}</span> 
                            <span class="info-box-number">   
                                <h:outputText value="#{stats}">
           							 <f:convertNumber type="percent" maxFractionDigits="3" />
        						</h:outputText>
                            </span>
                        </div>
                    </div>
</ui:composition>
</body>
</html>

src/main/webapp/WEB-INF/templates/inc/input-form-investment.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html">
<body>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:pe="http://primefaces.org/ui/extensions">

<c:if test="#{not empty instrument}">
    <c:set value="#{instrument}"  target="#{investmentDialog}"  property="investment" />

</c:if>

<p:dialog header="#{addInstrumentTitle}" widgetVar="#{widgetVar}" resizable="false" responsive="true"  modal="true" appendTo="@(body)" width="350" styleClass="card">
<h:form>
<f:facet name="header">
<i class="fa fa-file-invoice-dollar"></i> #{addInstrumentTitle}
</f:facet>
 <div class="ui-g ui-fluid psyinput">
 <div class="ui-g-5" >  <p:outputLabel value="Initial Deposit:"/></div>
                <div class="ui-g-7"><p:inputNumber 
                        value="#{investmentDialog.initialDeposit}" required="true" decimalSeparator=","
                        thousandSeparator="&nbsp;" emptyValue="0" decimalPlaces="2"
                        minValue="0" /> </div>


                <div class="ui-g-5"> <p:outputLabel value="Nominal Rate:"/></div>
                <div class="ui-g-7"><p:inputNumber 
                        value="#{investmentDialog.nominalRate}"
                        required="true" symbol="%" symbolPosition="s" decimalPlaces="1"
                        emptyValue="empty" minValue="0.1"/> </div>

                 <div class="ui-g-5"><p:outputLabel value="Term:"/> </div>
                 <div class="ui-g-7"> <p:inputNumber 
                        value="#{investmentDialog.termInMonths}" required="true"
                        emptyValue="empty" decimalPlaces="0" minValue="1" /> </div>


                 <div class="ui-g-5"><p:outputLabel value="Monthly Contribution:" /></div>
                 <div class="ui-g-7"> <p:inputNumber
                        value="#{investmentDialog.monthlyContribution}" symbolPosition="p"
                        decimalSeparator="," thousandSeparator="&nbsp;" emptyValue="empty"
                        decimalPlaces="2" minValue="0" /> </div>

                 <div class="ui-g-5"><p:outputLabel  value="Bank Fees:" /></div>
                <div class="ui-g-7"> <p:inputNumber 
                        value="#{investmentDialog.bankFees}" required="false" decimalSeparator=","
                        thousandSeparator="&nbsp;" emptyValue="empty" decimalPlaces="2"
                        minValue="0" /> </div>

                  <div class="ui-g-12">
                            <p:commandButton value="Calculate" ajax="false" icon="fa fa-fw fa-calculator" oncomplete="#{widgetVar}.hide()" action="#{submitAction}" styleClass="btn-primary" />
                        </div>
      </div>
</h:form>
</p:dialog>
</ui:composition>
</body>
</html>

src/main/webapp/WEB-INF/templates/inc/input-form-property-bond.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html">
<body>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:pe="http://primefaces.org/ui/extensions">

<p:dialog header="#{addInstrumentTitle}" widgetVar="#{widgetVar}" resizable="false" responsive="true"
                          modal="true" appendTo="@(body)" width="350" styleClass="card">
<h:form>

<c:if test="#{not empty instrument}">
    <c:set value="#{instrument}"  target="#{propertyBondDialog}"  property="propertyBond" />

</c:if>
                   <div class="ui-g ui-fluid psyinput">

               <div class="ui-g-5" >  <p:outputLabel value="Purchase Price:"/></div>
                <div class="ui-g-7"><p:inputNumber 
                        value="#{propertyBondDialog.purchasePrice}" required="true"
                        decimalSeparator="," thousandSeparator="&nbsp;" emptyValue="0"
                        decimalPlaces="2" minValue="0" /> </div>


                <div class="ui-g-5"> <p:outputLabel value="Interest Rate:"/></div>
                <div class="ui-g-7"><p:inputNumber 
                        value="#{propertyBondDialog.nominalRate}"
                        required="true" symbol="%" symbolPosition="s" decimalPlaces="1"
                        emptyValue="0" minValue="0.1" /> </div>

                 <div class="ui-g-5"><p:outputLabel value="Term:"/> </div>
                 <div class="ui-g-7"><p:inputNumber 
                        value="#{propertyBondDialog.termInMonths}" required="true"
                        emptyValue="0" decimalPlaces="0" minValue="1" /> </div>

                 <div class="ui-g-5"><p:outputLabel value="Initial Deposit: " /></div>
                 <div class="ui-g-7"><p:inputNumber 
                        value="#{propertyBondDialog.initialDepositRate}"
                        required="true" symbol="%" symbolPosition="s" decimalPlaces="1"
                        emptyValue="0" minValue="0" /> </div>

                 <div class="ui-g-5"><p:outputLabel value="Repayment: " /></div>
                 <div class="ui-g-7"><p:inputNumber
                        value="#{propertyBondDialog.monthlyRepayment}" required="true"
                        decimalSeparator="," thousandSeparator="&nbsp;" emptyValue="0"
                        decimalPlaces="2" minValue="0" /> </div>

                 <div class="ui-g-5"><p:outputLabel value="Bank Fees: " /></div>
                <div class="ui-g-7"><p:inputNumber
                        value="#{propertyBondDialog.bankFees}" required="true"
                        decimalSeparator="," thousandSeparator="&nbsp;" emptyValue="0"
                        decimalPlaces="2" minValue="0" /> </div>

                 

            <c:if test="#{giveFullForm}">
             <div class="ui-g-5">
                    <p:outputLabel  value="Bond Costs: " />
            </div>
            <div class="ui-g-7">
                <p:inputNumber
                    value="#{propertyBondDialog.bondCostsRate}"
                    required="true" symbol="%" symbolPosition="s" decimalPlaces="1"
                    emptyValue="0" minValue="0" />
            </div>
            <div class="ui-g-5">
                <p:outputLabel  value="Legal Fees: " />
            </div>
            <div class="ui-g-7">
                <p:inputNumber 
                    value="#{propertyBondDialog.legalFeesRate}"
                    required="true" symbol="%" symbolPosition="s" decimalPlaces="1"
                    emptyValue="0" minValue="0" />
            </div>

            </c:if>      

                  <div class="ui-g-12">
                            <p:commandButton value="Calculate" icon="fa fa-fw fa-calculator"  oncomplete="#{widgetVar}.hide()" action="#{submitAction}" styleClass="btn-primary" ajax="false"/>
                        </div>
                  </div>
                </h:form>
            </p:dialog>
</ui:composition>
</body>
</html>